= Learning Terraform on Azure

Taking the course https://www.udemy.com/course/learning-terraform-on-microsoft-azure/

== Setup

To use Terraform with Azure. You will need to export the following variables.
[source,bash]
----
export ARM_CLIENT_ID="xxx"
export ARM_CLIENT_SECRET="xxx"
export ARM_TENANT_ID="xxx"
export ARM_SUBSCRIPTION_ID="xxx"
----
In this directory I created `.env` with the above so that I can source it into the CLI with
`. ./.env`.

== Learning's

1. Create remote Terraform state repository
2. Create vault for secrets
3. After reading/watching https://www.hashicorp.com/resources/lessons-learned-300000-lines-code
it is best to keep things separate based on deployment. Hence, why `vault` is in a different folder
as well as `tfstate`.
4. In real world `vault` and `web` directories would contain sub folders of environments (dev,
test, stage, prod...)... possibly. I could fight both of something meant for dev being deployed to
production because of the wrong variable set. But, I can also see being in the wrong folder and
having the same problem.

== Pondering's

1. Breaking down the web module further (firewall, load balancer...)
2. Place the traffic manager in a module? Do the traffic_manager endpoints belong in the web module?
    a. Port number 80 is disjointed from the firewall in the web module and the traffic manager.
        Best way to resolve?
    b. Should traffic manager resource group and profile be in a separate folder? How does this
        help with sub point a?
3. Should bastion be a part of the web module?
4. If this was the real world wouldn't I just be deploying updated vm's? Once the
network infrastructure is there I don't think I would want to create that every time.

== Next steps

1. Get the vault data from the terraform backend output
2. Move traffic manager rg and profile to it's own directory
3. Move traffic manager endpoints to web module
4. Move bastion to web module
5. Separate the web server vm deployments from the networking pieces.
6. Create Dev Prod folders.
